[2024-05-09T16:57:03.660+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T16:57:03.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_query.mysql_query manual__2024-05-09T16:56:50.301848+00:00 [queued]>
[2024-05-09T16:57:03.748+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_query.mysql_query manual__2024-05-09T16:56:50.301848+00:00 [queued]>
[2024-05-09T16:57:03.749+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T16:57:03.790+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): mysql_query> on 2024-05-09 16:56:50.301848+00:00
[2024-05-09T16:57:03.802+0000] {standard_task_runner.py:63} INFO - Started process 156 to run task
[2024-05-09T16:57:03.808+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_query', 'mysql_query', 'manual__2024-05-09T16:56:50.301848+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/mysql_query.py', '--cfg-path', '/tmp/tmpp3orp3cy']
[2024-05-09T16:57:03.816+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask mysql_query
[2024-05-09T16:57:03.950+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_query.mysql_query manual__2024-05-09T16:56:50.301848+00:00 [running]> on host a602b01b49ab
[2024-05-09T16:57:04.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_query' AIRFLOW_CTX_TASK_ID='mysql_query' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T16:56:50.301848+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T16:56:50.301848+00:00'
[2024-05-09T16:57:04.203+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T16:57:04.205+0000] {sql.py:276} INFO - Executing: SELECT * FROM dibimbing.karyawan
[2024-05-09T16:57:04.236+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T16:57:04.262+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_default` isn't defined
[2024-05-09T16:57:04.271+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mysql_query, task_id=mysql_query, run_id=manual__2024-05-09T16:56:50.301848+00:00, execution_date=20240509T165650, start_date=20240509T165703, end_date=20240509T165704
[2024-05-09T16:57:04.305+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task mysql_query (The conn_id `mysql_default` isn't defined; 156)
[2024-05-09T16:57:04.350+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T16:57:04.376+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-09T16:57:04.407+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T16:57:04.415+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
