[2024-05-05T07:10:29.851+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T07:10:30.013+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: passing_data_with_variable.prev_variable manual__2024-05-05T07:10:18.888733+00:00 [queued]>
[2024-05-05T07:10:30.089+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: passing_data_with_variable.prev_variable manual__2024-05-05T07:10:18.888733+00:00 [queued]>
[2024-05-05T07:10:30.099+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T07:10:30.300+0000] {taskinstance.py:2327} INFO - Executing <Task(_PythonDecoratedOperator): prev_variable> on 2024-05-05 07:10:18.888733+00:00
[2024-05-05T07:10:30.347+0000] {standard_task_runner.py:63} INFO - Started process 218 to run task
[2024-05-05T07:10:30.360+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'passing_data_with_variable', 'prev_variable', 'manual__2024-05-05T07:10:18.888733+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/passing_data_with_variable.py', '--cfg-path', '/tmp/tmpui1cr8cf']
[2024-05-05T07:10:30.383+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask prev_variable
[2024-05-05T07:10:30.790+0000] {task_command.py:426} INFO - Running <TaskInstance: passing_data_with_variable.prev_variable manual__2024-05-05T07:10:18.888733+00:00 [running]> on host 20826f80b84b
[2024-05-05T07:10:31.640+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='passing_data_with_variable' AIRFLOW_CTX_TASK_ID='prev_variable' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T07:10:18.888733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T07:10:18.888733+00:00'
[2024-05-05T07:10:31.658+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T07:10:31.722+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T07:10:31.731+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/passing_data_with_variable.py", line 15, in prev_variable
    var = Variable.get("data_variable", deserialize_json=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable data_variable does not exist'
[2024-05-05T07:10:31.827+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=passing_data_with_variable, task_id=prev_variable, execution_date=20240505T071018, start_date=20240505T071030, end_date=20240505T071031
[2024-05-05T07:10:31.900+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task prev_variable ('Variable data_variable does not exist'; 218)
[2024-05-05T07:10:31.979+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T07:10:32.248+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T07:10:32.287+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
