[2024-07-02T16:00:06.056+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:00:06.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:00:06.071+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:00:06.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:00:06.213+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:00:06.193+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:00:06.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:00:06.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.299 seconds
[2024-07-02T16:00:46.805+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:00:46.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:00:46.822+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:00:46.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:00:46.922+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:00:46.907+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:00:46.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:00:47.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.272 seconds
[2024-07-02T16:01:10.901+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:10.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:01:10.916+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:10.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:11.003+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:10.987+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:01:11.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:11.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.244 seconds
[2024-07-02T16:01:30.344+0000] {processor.py:161} INFO - Started process (PID=367) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:30.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:01:30.351+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:30.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:30.380+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:30.373+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:01:30.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:30.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.088 seconds
[2024-07-02T16:01:43.982+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:43.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:01:43.987+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:43.987+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:44.015+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:44.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:01:44.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:44.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.089 seconds
[2024-07-02T16:01:59.674+0000] {processor.py:161} INFO - Started process (PID=538) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:59.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:01:59.681+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:59.681+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:59.758+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:59.748+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:01:59.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:01:59.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.184 seconds
[2024-07-02T16:02:15.533+0000] {processor.py:161} INFO - Started process (PID=627) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:15.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:02:15.540+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:15.539+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:15.570+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:15.563+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:02:15.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:15.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.099 seconds
[2024-07-02T16:02:40.248+0000] {processor.py:161} INFO - Started process (PID=716) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:40.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:02:40.254+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:40.253+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:40.297+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:40.291+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:02:40.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:40.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.121 seconds
[2024-07-02T16:02:54.847+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:54.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:02:54.852+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:54.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:54.887+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:54.881+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:02:54.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:02:54.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.094 seconds
[2024-07-02T16:03:14.071+0000] {processor.py:161} INFO - Started process (PID=886) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:14.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:03:14.075+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:14.075+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:14.093+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:14.089+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:03:14.098+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:14.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.141 seconds
[2024-07-02T16:03:32.654+0000] {processor.py:161} INFO - Started process (PID=969) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:32.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:03:32.659+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:32.659+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:32.692+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:32.685+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:03:32.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:32.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.184 seconds
[2024-07-02T16:03:48.222+0000] {processor.py:161} INFO - Started process (PID=1058) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:48.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:03:48.228+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:48.227+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:48.262+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:48.254+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:03:48.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:03:48.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.407 seconds
[2024-07-02T16:04:11.464+0000] {processor.py:161} INFO - Started process (PID=1146) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:04:11.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:04:11.469+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:04:11.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:04:11.493+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:04:11.487+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:04:11.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:04:11.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.296 seconds
[2024-07-02T16:04:38.405+0000] {processor.py:161} INFO - Started process (PID=1233) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:04:38.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:04:38.444+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:04:38.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:04:38.625+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:04:38.610+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:04:38.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:04:39.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.878 seconds
[2024-07-02T16:05:05.041+0000] {processor.py:161} INFO - Started process (PID=1315) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:05:05.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:05:05.054+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:05:05.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:05:05.224+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:05:05.194+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:05:05.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:05:05.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.309 seconds
[2024-07-02T16:05:32.513+0000] {processor.py:161} INFO - Started process (PID=1403) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:05:32.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:05:32.530+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:05:32.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:05:32.595+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:05:32.578+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:05:32.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:05:32.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.271 seconds
[2024-07-02T16:06:10.624+0000] {processor.py:161} INFO - Started process (PID=1497) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:06:10.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:06:10.645+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:06:10.644+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:06:10.758+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:06:10.739+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:06:10.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:06:10.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.278 seconds
[2024-07-02T16:06:46.904+0000] {processor.py:161} INFO - Started process (PID=1586) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:06:46.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:06:46.921+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:06:46.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:06:47.010+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:06:46.982+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:06:47.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:06:47.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.334 seconds
[2024-07-02T16:07:34.258+0000] {processor.py:161} INFO - Started process (PID=1674) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:07:34.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:07:34.336+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:07:34.330+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:07:35.089+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:07:34.945+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:07:35.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:07:36.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 2.332 seconds
[2024-07-02T16:09:04.399+0000] {processor.py:161} INFO - Started process (PID=1773) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:09:04.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:09:04.414+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:09:04.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:09:04.526+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:09:04.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:09:04.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:09:04.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.315 seconds
[2024-07-02T16:09:57.572+0000] {processor.py:161} INFO - Started process (PID=1865) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:09:57.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:09:57.584+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:09:57.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:09:57.684+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:09:57.656+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:09:57.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:09:57.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.266 seconds
[2024-07-02T16:11:42.241+0000] {processor.py:161} INFO - Started process (PID=1964) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:11:42.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:11:42.259+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:11:42.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:11:42.366+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:11:42.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:11:42.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:11:42.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.258 seconds
[2024-07-02T16:12:28.883+0000] {processor.py:161} INFO - Started process (PID=2058) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:12:28.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:12:28.900+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:12:28.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:12:29.022+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:12:29.010+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:12:29.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:12:29.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.256 seconds
[2024-07-02T16:13:58.163+0000] {processor.py:161} INFO - Started process (PID=2155) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:13:58.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:13:58.191+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:13:58.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:13:58.402+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:13:58.372+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:13:58.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:13:58.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.389 seconds
[2024-07-02T16:15:33.480+0000] {processor.py:161} INFO - Started process (PID=2255) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:15:34.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:15:36.278+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:15:36.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:15:36.863+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:15:36.803+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:15:36.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:15:38.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 5.322 seconds
[2024-07-02T16:17:14.484+0000] {processor.py:161} INFO - Started process (PID=2355) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:17:14.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:17:14.514+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:17:14.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:17:14.770+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:17:14.686+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:17:14.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:17:15.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 1.031 seconds
[2024-07-02T16:18:42.319+0000] {processor.py:161} INFO - Started process (PID=2455) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:18:42.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:18:42.339+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:18:42.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:18:42.450+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:18:42.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:18:42.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:18:42.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.287 seconds
[2024-07-02T16:19:54.784+0000] {processor.py:161} INFO - Started process (PID=2547) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:19:54.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:19:54.834+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:19:54.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:19:54.992+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:19:54.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:19:55.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:19:55.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.480 seconds
[2024-07-02T16:20:58.088+0000] {processor.py:161} INFO - Started process (PID=2641) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:20:58.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:20:58.126+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:20:58.125+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:20:58.393+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:20:58.377+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:20:58.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:20:58.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.523 seconds
[2024-07-02T16:21:30.122+0000] {processor.py:161} INFO - Started process (PID=2730) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:21:30.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:21:30.129+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:21:30.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:21:30.158+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:21:30.151+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:21:30.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:21:30.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.094 seconds
[2024-07-02T16:21:53.548+0000] {processor.py:161} INFO - Started process (PID=2817) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:21:53.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:21:53.570+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:21:53.569+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:21:53.659+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:21:53.644+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:21:53.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:21:53.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.286 seconds
[2024-07-02T16:22:38.374+0000] {processor.py:161} INFO - Started process (PID=2912) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:22:38.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:22:38.398+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:22:38.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:22:38.646+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:22:38.612+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:22:38.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:22:38.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.429 seconds
[2024-07-02T16:23:38.620+0000] {processor.py:161} INFO - Started process (PID=3006) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:23:38.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:23:38.665+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:23:38.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:23:38.829+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:23:38.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:23:38.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:23:38.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.409 seconds
[2024-07-02T16:25:34.428+0000] {processor.py:161} INFO - Started process (PID=3107) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:25:34.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:25:34.487+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:25:34.483+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:25:34.758+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:25:34.685+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:25:34.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:25:35.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.988 seconds
[2024-07-02T16:27:18.787+0000] {processor.py:161} INFO - Started process (PID=3213) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:27:19.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:27:19.759+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:27:19.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:27:20.453+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:27:20.255+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:27:20.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:27:22.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 4.338 seconds
[2024-07-02T16:29:06.524+0000] {processor.py:161} INFO - Started process (PID=3311) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:29:06.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:29:06.551+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:29:06.540+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:29:07.021+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:29:06.953+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:29:07.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:29:07.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.740 seconds
[2024-07-02T16:29:57.596+0000] {processor.py:161} INFO - Started process (PID=3404) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:29:57.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:29:57.609+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:29:57.608+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:29:57.649+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:29:57.640+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:29:57.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:29:57.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.204 seconds
[2024-07-02T16:30:23.946+0000] {processor.py:161} INFO - Started process (PID=3486) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:30:23.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:30:23.957+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:30:23.955+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:30:24.018+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:30:24.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:30:24.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:30:24.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.182 seconds
[2024-07-02T16:31:12.673+0000] {processor.py:161} INFO - Started process (PID=3580) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:31:12.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:31:13.177+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:31:13.134+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:31:14.584+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:31:14.559+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:31:14.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:31:14.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 2.728 seconds
[2024-07-02T16:31:51.329+0000] {processor.py:161} INFO - Started process (PID=3667) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:31:51.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:31:51.344+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:31:51.343+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:31:52.479+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:31:51.462+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:31:52.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:31:54.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 3.656 seconds
[2024-07-02T16:32:42.366+0000] {processor.py:161} INFO - Started process (PID=3763) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:32:42.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:32:42.384+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:32:42.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:32:42.525+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:32:42.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:32:42.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:32:43.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.748 seconds
[2024-07-02T16:33:13.343+0000] {processor.py:161} INFO - Started process (PID=3851) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:33:13.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:33:13.377+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:33:13.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:33:13.484+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:33:13.471+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:33:13.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:33:13.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.250 seconds
[2024-07-02T16:33:50.673+0000] {processor.py:161} INFO - Started process (PID=3939) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:33:50.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:33:50.720+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:33:50.719+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:33:50.915+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:33:50.874+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:33:50.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:33:51.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.470 seconds
[2024-07-02T16:34:39.196+0000] {processor.py:161} INFO - Started process (PID=4033) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:34:39.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:34:39.220+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:34:39.218+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:34:39.470+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:34:39.383+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:34:39.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:34:40.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 1.015 seconds
[2024-07-02T16:35:10.469+0000] {processor.py:161} INFO - Started process (PID=4121) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:35:10.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:35:10.481+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:35:10.480+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:35:10.581+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:35:10.561+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:35:10.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:35:10.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.253 seconds
[2024-07-02T16:35:53.488+0000] {processor.py:161} INFO - Started process (PID=4209) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:35:53.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:35:53.510+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:35:53.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:35:53.661+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:35:53.643+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:35:53.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:35:53.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.301 seconds
[2024-07-02T16:36:26.872+0000] {processor.py:161} INFO - Started process (PID=4297) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:36:26.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:36:26.905+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:36:26.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:36:27.023+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:36:27.000+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:36:27.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:36:27.141+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.321 seconds
[2024-07-02T16:37:15.928+0000] {processor.py:161} INFO - Started process (PID=4391) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:37:15.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:37:15.953+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:37:15.952+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:37:16.056+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:37:16.036+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:37:16.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:37:16.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.257 seconds
[2024-07-02T16:37:43.560+0000] {processor.py:161} INFO - Started process (PID=4479) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:37:43.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:37:43.572+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:37:43.571+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:37:43.636+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:37:43.620+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:37:43.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:37:43.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.222 seconds
[2024-07-02T16:38:01.253+0000] {processor.py:161} INFO - Started process (PID=4561) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:01.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:38:01.277+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:01.276+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:01.463+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:01.447+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:38:01.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:01.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.338 seconds
[2024-07-02T16:38:17.269+0000] {processor.py:161} INFO - Started process (PID=4650) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:17.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:38:17.274+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:17.274+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:17.298+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:17.292+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:38:17.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:17.332+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.074 seconds
[2024-07-02T16:38:32.861+0000] {processor.py:161} INFO - Started process (PID=4732) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:32.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:38:32.870+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:32.868+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:32.914+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:32.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:38:32.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:32.980+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.141 seconds
[2024-07-02T16:38:49.772+0000] {processor.py:161} INFO - Started process (PID=4821) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:49.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:38:49.781+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:49.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:49.817+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:49.810+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:38:49.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:38:49.859+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.104 seconds
[2024-07-02T16:39:00.512+0000] {processor.py:161} INFO - Started process (PID=4903) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:00.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:39:00.519+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:00.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:00.554+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:00.545+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:39:00.557+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:00.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.103 seconds
[2024-07-02T16:39:15.869+0000] {processor.py:161} INFO - Started process (PID=4992) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:15.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:39:15.876+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:15.876+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:15.916+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:15.906+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:39:15.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:15.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.139 seconds
[2024-07-02T16:39:33.636+0000] {processor.py:161} INFO - Started process (PID=5074) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:33.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:39:33.643+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:33.643+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:33.675+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:33.668+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:39:33.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:33.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.107 seconds
[2024-07-02T16:39:46.342+0000] {processor.py:161} INFO - Started process (PID=5162) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:46.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:39:46.352+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:46.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:46.387+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:46.378+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:39:46.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:46.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.122 seconds
[2024-07-02T16:39:59.263+0000] {processor.py:161} INFO - Started process (PID=5244) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:59.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:39:59.272+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:59.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:59.305+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:59.297+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:39:59.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:39:59.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.120 seconds
[2024-07-02T16:40:10.487+0000] {processor.py:161} INFO - Started process (PID=5332) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:10.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:40:10.495+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:10.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:10.532+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:10.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:40:10.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:10.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.117 seconds
[2024-07-02T16:40:22.134+0000] {processor.py:161} INFO - Started process (PID=5414) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:22.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:40:22.147+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:22.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:22.192+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:22.182+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:40:22.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:22.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.158 seconds
[2024-07-02T16:40:34.684+0000] {processor.py:161} INFO - Started process (PID=5496) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:34.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:40:34.689+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:34.688+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:34.720+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:34.714+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:40:34.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:34.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.082 seconds
[2024-07-02T16:40:44.176+0000] {processor.py:161} INFO - Started process (PID=5585) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:44.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:40:44.185+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:44.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:44.221+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:44.211+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:40:44.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:44.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.136 seconds
[2024-07-02T16:40:53.510+0000] {processor.py:161} INFO - Started process (PID=5667) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:53.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:40:53.516+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:53.515+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:53.543+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:53.537+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:40:53.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:40:53.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.085 seconds
[2024-07-02T16:41:03.096+0000] {processor.py:161} INFO - Started process (PID=5749) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:03.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:41:03.102+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:03.101+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:03.130+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:03.123+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:41:03.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:03.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.083 seconds
[2024-07-02T16:41:12.508+0000] {processor.py:161} INFO - Started process (PID=5837) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:12.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:41:12.513+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:12.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:12.539+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:12.532+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:41:12.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:12.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.080 seconds
[2024-07-02T16:41:22.505+0000] {processor.py:161} INFO - Started process (PID=5919) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:22.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:41:22.513+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:22.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:22.560+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:22.552+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:41:22.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:22.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.115 seconds
[2024-07-02T16:41:30.649+0000] {processor.py:161} INFO - Started process (PID=6001) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:30.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:41:30.654+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:30.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:30.677+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:30.671+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:41:30.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:30.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.078 seconds
[2024-07-02T16:41:40.679+0000] {processor.py:161} INFO - Started process (PID=6089) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:40.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:41:40.685+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:40.684+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:40.716+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:40.709+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:41:40.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:40.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.093 seconds
[2024-07-02T16:41:50.110+0000] {processor.py:161} INFO - Started process (PID=6171) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:50.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:41:50.117+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:50.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:50.149+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:50.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:41:50.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:50.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.098 seconds
[2024-07-02T16:41:59.962+0000] {processor.py:161} INFO - Started process (PID=6253) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:41:59.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:41:59.967+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:59.967+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:00.000+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:59.993+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:42:00.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:00.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.089 seconds
[2024-07-02T16:42:09.123+0000] {processor.py:161} INFO - Started process (PID=6341) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:09.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:42:09.128+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:09.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:09.155+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:09.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:42:09.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:09.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.088 seconds
[2024-07-02T16:42:18.702+0000] {processor.py:161} INFO - Started process (PID=6423) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:18.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:42:18.708+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:18.707+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:18.733+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:18.728+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:42:18.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:18.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.076 seconds
[2024-07-02T16:42:27.602+0000] {processor.py:161} INFO - Started process (PID=6505) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:27.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:42:27.608+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:27.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:27.637+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:27.629+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:42:27.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:27.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.107 seconds
[2024-07-02T16:42:42.417+0000] {processor.py:161} INFO - Started process (PID=6594) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:42.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:42:42.422+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:42.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:42.450+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:42.444+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:42:42.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:42.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.081 seconds
[2024-07-02T16:42:54.185+0000] {processor.py:161} INFO - Started process (PID=6677) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:54.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:42:54.188+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:54.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:54.219+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:54.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:42:54.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:42:54.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.083 seconds
[2024-07-02T16:43:04.510+0000] {processor.py:161} INFO - Started process (PID=6760) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:04.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:43:04.513+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:04.513+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:04.545+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:04.537+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:43:04.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:04.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.085 seconds
[2024-07-02T16:43:16.771+0000] {processor.py:161} INFO - Started process (PID=6849) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:16.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:43:16.776+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:16.775+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:16.808+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:16.800+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:43:16.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:16.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.097 seconds
[2024-07-02T16:43:29.647+0000] {processor.py:161} INFO - Started process (PID=6932) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:29.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:43:29.671+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:29.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:29.719+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:29.711+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:43:29.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:29.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.236 seconds
[2024-07-02T16:43:41.335+0000] {processor.py:161} INFO - Started process (PID=7021) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:41.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:43:41.342+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:41.341+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:41.375+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:41.367+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:43:41.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:41.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.126 seconds
[2024-07-02T16:43:54.751+0000] {processor.py:161} INFO - Started process (PID=7104) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:54.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:43:54.754+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:54.753+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:54.786+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:54.778+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:43:54.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:43:54.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.082 seconds
[2024-07-02T16:44:05.109+0000] {processor.py:161} INFO - Started process (PID=7187) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:05.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:44:05.114+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:05.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:05.149+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:05.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:44:05.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:05.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.108 seconds
[2024-07-02T16:44:14.678+0000] {processor.py:161} INFO - Started process (PID=7276) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:14.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:44:14.683+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:14.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:14.713+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:14.706+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:44:14.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:14.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.099 seconds
[2024-07-02T16:44:25.669+0000] {processor.py:161} INFO - Started process (PID=7359) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:25.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:44:25.676+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:25.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:25.708+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:25.700+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:44:25.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:25.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.098 seconds
[2024-07-02T16:44:37.993+0000] {processor.py:161} INFO - Started process (PID=7448) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:37.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:44:38.000+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:37.999+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:38.043+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:38.031+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:44:38.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:38.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.136 seconds
[2024-07-02T16:44:49.541+0000] {processor.py:161} INFO - Started process (PID=7532) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:49.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:44:49.545+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:49.544+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:49.575+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:49.568+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:44:49.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:44:49.611+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.081 seconds
[2024-07-02T16:45:00.302+0000] {processor.py:161} INFO - Started process (PID=7615) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:00.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:45:00.305+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:00.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:00.328+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:00.322+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:45:00.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:00.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.070 seconds
[2024-07-02T16:45:09.918+0000] {processor.py:161} INFO - Started process (PID=7704) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:09.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:45:09.921+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:09.921+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:09.949+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:09.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:45:09.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:09.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.076 seconds
[2024-07-02T16:45:22.968+0000] {processor.py:161} INFO - Started process (PID=7787) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:22.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:45:22.971+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:22.971+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:23.002+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:22.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:45:23.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:23.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.078 seconds
[2024-07-02T16:45:35.181+0000] {processor.py:161} INFO - Started process (PID=7870) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:35.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:45:35.186+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:35.185+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:35.219+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:35.210+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:45:35.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:35.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.088 seconds
[2024-07-02T16:45:49.278+0000] {processor.py:161} INFO - Started process (PID=7959) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:49.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:45:49.285+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:49.284+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:49.324+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:49.316+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:45:49.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:45:49.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.113 seconds
[2024-07-02T16:46:03.827+0000] {processor.py:161} INFO - Started process (PID=8042) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:03.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:46:03.831+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:03.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:03.864+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:03.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:46:03.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:03.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.098 seconds
[2024-07-02T16:46:24.348+0000] {processor.py:161} INFO - Started process (PID=8131) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:24.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:46:24.352+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:24.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:24.378+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:24.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:46:24.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:24.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.084 seconds
[2024-07-02T16:46:39.913+0000] {processor.py:161} INFO - Started process (PID=8220) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:39.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:46:39.916+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:39.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:39.945+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:39.938+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:46:39.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:39.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.076 seconds
[2024-07-02T16:46:48.555+0000] {processor.py:161} INFO - Started process (PID=8303) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:48.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:46:48.558+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:48.558+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:48.590+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:48.582+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:46:48.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:48.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.083 seconds
[2024-07-02T16:46:58.581+0000] {processor.py:161} INFO - Started process (PID=8386) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:58.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:46:58.584+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:58.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:58.611+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:58.604+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:46:58.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:46:58.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.091 seconds
[2024-07-02T16:47:08.994+0000] {processor.py:161} INFO - Started process (PID=8475) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:08.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:47:08.998+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:08.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:09.026+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:09.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:47:09.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:09.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.085 seconds
[2024-07-02T16:47:18.683+0000] {processor.py:161} INFO - Started process (PID=8559) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:18.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:47:18.689+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:18.688+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:18.718+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:18.711+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:47:18.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:18.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.093 seconds
[2024-07-02T16:47:27.239+0000] {processor.py:161} INFO - Started process (PID=8642) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:27.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:47:27.242+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:27.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:27.271+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:27.265+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:47:27.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:27.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.080 seconds
[2024-07-02T16:47:37.601+0000] {processor.py:161} INFO - Started process (PID=8725) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:37.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:47:37.605+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:37.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:37.629+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:37.623+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:47:37.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:37.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.077 seconds
[2024-07-02T16:47:47.499+0000] {processor.py:161} INFO - Started process (PID=8814) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:47.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:47:47.503+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:47.503+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:47.537+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:47.529+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:47:47.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:47.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.087 seconds
[2024-07-02T16:47:58.264+0000] {processor.py:161} INFO - Started process (PID=8897) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:58.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:47:58.267+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:58.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:58.300+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:58.292+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:47:58.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:47:58.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.090 seconds
[2024-07-02T16:48:15.249+0000] {processor.py:161} INFO - Started process (PID=8986) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:15.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:48:15.255+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:15.254+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:15.297+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:15.287+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:48:15.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:15.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.144 seconds
[2024-07-02T16:48:27.236+0000] {processor.py:161} INFO - Started process (PID=9069) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:27.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:48:27.240+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:27.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:27.268+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:27.261+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:48:27.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:27.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.086 seconds
[2024-07-02T16:48:37.373+0000] {processor.py:161} INFO - Started process (PID=9153) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:37.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:48:37.378+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:37.377+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:37.404+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:37.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:48:37.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:37.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.087 seconds
[2024-07-02T16:48:53.569+0000] {processor.py:161} INFO - Started process (PID=9243) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:53.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:48:53.573+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:53.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:53.599+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:53.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ecommerce_etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ecommerce_etl_pipeline.py", line 3, in <module>
    from airflow.contrib.operators.s3_to_gcs_operator import S3ToGoogleCloudStorageOperator
ImportError: cannot import name 'S3ToGoogleCloudStorageOperator' from 'airflow.contrib.operators.s3_to_gcs_operator' (unknown location)
[2024-07-02T16:48:53.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:48:53.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.088 seconds
[2024-07-02T16:49:08.659+0000] {processor.py:161} INFO - Started process (PID=9332) to work on /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:49:08.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ecommerce_etl_pipeline.py for tasks to queue
[2024-07-02T16:49:08.663+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:49:08.663+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:49:08.667+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ecommerce_etl_pipeline.py
[2024-07-02T16:49:08.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ecommerce_etl_pipeline.py took 0.049 seconds
