[2024-07-02T16:00:04.419+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:00:04.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:00:04.446+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:00:04.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:00:04.597+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:00:04.583+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:00:04.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:00:04.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.313 seconds
[2024-07-02T16:00:45.546+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:00:45.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:00:45.583+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:00:45.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:00:45.818+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:00:45.729+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:00:45.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:00:45.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.403 seconds
[2024-07-02T16:01:10.037+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:10.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:01:10.044+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:10.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:10.101+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:10.088+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:01:10.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:10.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.234 seconds
[2024-07-02T16:01:29.948+0000] {processor.py:161} INFO - Started process (PID=365) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:29.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:01:29.954+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:29.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:30.017+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:30.007+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:01:30.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:30.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.106 seconds
[2024-07-02T16:01:43.570+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:43.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:01:43.575+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:43.575+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:43.625+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:43.618+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:01:43.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:43.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.134 seconds
[2024-07-02T16:01:59.474+0000] {processor.py:161} INFO - Started process (PID=536) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:59.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:01:59.481+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:59.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:59.542+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:01:59.536+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:01:59.545+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:01:59.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.114 seconds
[2024-07-02T16:02:15.103+0000] {processor.py:161} INFO - Started process (PID=625) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:15.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:02:15.108+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:15.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:15.168+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:15.159+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:02:15.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:15.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.098 seconds
[2024-07-02T16:02:40.004+0000] {processor.py:161} INFO - Started process (PID=714) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:40.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:02:40.011+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:40.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:40.102+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:40.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:02:40.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:40.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.158 seconds
[2024-07-02T16:02:54.569+0000] {processor.py:161} INFO - Started process (PID=796) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:54.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:02:54.573+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:54.573+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:54.642+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:02:54.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:02:54.645+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:02:54.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.118 seconds
[2024-07-02T16:03:13.426+0000] {processor.py:161} INFO - Started process (PID=884) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:13.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:03:13.430+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:13.430+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:13.481+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:13.474+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:03:13.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:13.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.203 seconds
[2024-07-02T16:03:31.908+0000] {processor.py:161} INFO - Started process (PID=966) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:31.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:03:31.916+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:31.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:32.017+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:32.004+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:03:32.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:32.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.296 seconds
[2024-07-02T16:03:47.539+0000] {processor.py:161} INFO - Started process (PID=1056) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:47.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:03:47.546+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:47.546+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:47.596+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:03:47.589+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:03:47.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:03:47.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.214 seconds
[2024-07-02T16:04:10.558+0000] {processor.py:161} INFO - Started process (PID=1144) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:04:10.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:04:10.563+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:04:10.562+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:04:10.696+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:04:10.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:04:10.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:04:10.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.394 seconds
[2024-07-02T16:04:36.347+0000] {processor.py:161} INFO - Started process (PID=1225) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:04:36.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:04:36.359+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:04:36.359+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:04:36.590+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:04:36.552+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:04:36.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:04:36.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.374 seconds
[2024-07-02T16:05:04.262+0000] {processor.py:161} INFO - Started process (PID=1313) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:05:04.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:05:04.278+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:05:04.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:05:04.463+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:05:04.422+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:05:04.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:05:04.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.279 seconds
[2024-07-02T16:05:31.638+0000] {processor.py:161} INFO - Started process (PID=1401) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:05:31.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:05:31.655+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:05:31.654+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:05:31.774+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:05:31.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:05:31.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:05:31.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.207 seconds
[2024-07-02T16:06:09.124+0000] {processor.py:161} INFO - Started process (PID=1495) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:06:09.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:06:09.146+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:06:09.144+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:06:09.357+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:06:09.335+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:06:09.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:06:09.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.557 seconds
[2024-07-02T16:06:45.207+0000] {processor.py:161} INFO - Started process (PID=1584) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:06:45.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:06:45.240+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:06:45.238+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:06:45.439+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:06:45.428+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:06:45.468+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:06:45.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.393 seconds
[2024-07-02T16:07:21.210+0000] {processor.py:161} INFO - Started process (PID=1672) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:07:21.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:07:21.251+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:07:21.246+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:07:22.748+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:07:22.498+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:07:22.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:07:23.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 2.476 seconds
[2024-07-02T16:09:00.965+0000] {processor.py:161} INFO - Started process (PID=1771) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:09:00.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:09:00.975+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:09:00.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:09:01.613+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:09:01.454+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:09:01.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:09:01.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 1.286 seconds
[2024-07-02T16:09:55.591+0000] {processor.py:161} INFO - Started process (PID=1863) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:09:55.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:09:55.660+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:09:55.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:09:56.081+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:09:56.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:09:56.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:09:56.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.863 seconds
[2024-07-02T16:11:40.839+0000] {processor.py:161} INFO - Started process (PID=1962) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:11:40.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:11:40.859+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:11:40.858+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:11:41.163+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:11:41.054+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:11:41.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:11:41.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.585 seconds
[2024-07-02T16:12:28.006+0000] {processor.py:161} INFO - Started process (PID=2056) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:12:28.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:12:28.018+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:12:28.017+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:12:28.157+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:12:28.142+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:12:28.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:12:28.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.234 seconds
[2024-07-02T16:13:56.646+0000] {processor.py:161} INFO - Started process (PID=2153) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:13:56.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:13:56.673+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:13:56.672+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:13:56.934+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:13:56.875+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:13:56.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:13:57.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.403 seconds
[2024-07-02T16:15:23.448+0000] {processor.py:161} INFO - Started process (PID=2246) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:15:23.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:15:23.459+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:15:23.458+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:15:23.910+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:15:23.804+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:15:23.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:15:24.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.877 seconds
[2024-07-02T16:17:13.221+0000] {processor.py:161} INFO - Started process (PID=2352) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:17:13.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:17:13.238+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:17:13.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:17:13.399+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:17:13.376+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:17:13.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:17:13.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.286 seconds
[2024-07-02T16:18:40.866+0000] {processor.py:161} INFO - Started process (PID=2453) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:18:40.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:18:40.908+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:18:40.907+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:18:41.150+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:18:41.116+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:18:41.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:18:41.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.402 seconds
[2024-07-02T16:19:52.722+0000] {processor.py:161} INFO - Started process (PID=2545) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:19:52.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:19:52.740+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:19:52.739+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:19:53.083+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:19:53.046+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:19:53.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:19:53.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.559 seconds
[2024-07-02T16:20:52.986+0000] {processor.py:161} INFO - Started process (PID=2639) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:20:53.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:20:53.241+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:20:53.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:20:54.370+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:20:54.287+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:20:54.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:20:54.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 2.574 seconds
[2024-07-02T16:21:27.265+0000] {processor.py:161} INFO - Started process (PID=2728) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:21:27.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:21:27.285+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:21:27.284+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:21:27.437+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:21:27.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:21:27.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:21:27.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.235 seconds
[2024-07-02T16:21:52.012+0000] {processor.py:161} INFO - Started process (PID=2815) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:21:52.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:21:52.057+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:21:52.054+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:21:52.435+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:21:52.423+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:21:52.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:21:52.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.541 seconds
[2024-07-02T16:22:36.706+0000] {processor.py:161} INFO - Started process (PID=2910) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:22:36.734+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:22:36.757+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:22:36.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:22:37.106+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:22:37.088+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:22:37.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:22:37.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.808 seconds
[2024-07-02T16:23:36.399+0000] {processor.py:161} INFO - Started process (PID=3003) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:23:36.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:23:36.428+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:23:36.418+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:23:36.768+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:23:36.722+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:23:36.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:23:36.855+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.548 seconds
[2024-07-02T16:25:26.187+0000] {processor.py:161} INFO - Started process (PID=3105) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:25:26.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:25:26.321+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:25:26.310+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:25:26.940+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:25:26.827+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:25:26.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:25:27.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 1.447 seconds
[2024-07-02T16:27:09.142+0000] {processor.py:161} INFO - Started process (PID=3205) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:27:09.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:27:09.165+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:27:09.163+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:27:09.606+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:27:09.485+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:27:09.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:27:09.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.745 seconds
[2024-07-02T16:29:04.543+0000] {processor.py:161} INFO - Started process (PID=3309) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:29:04.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:29:04.561+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:29:04.560+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:29:04.885+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:29:04.821+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:29:04.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:29:04.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.467 seconds
[2024-07-02T16:29:54.477+0000] {processor.py:161} INFO - Started process (PID=3396) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:29:54.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:29:54.569+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:29:54.561+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:29:55.157+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:29:55.128+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:29:55.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:29:55.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.963 seconds
[2024-07-02T16:30:23.315+0000] {processor.py:161} INFO - Started process (PID=3484) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:30:23.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:30:23.326+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:30:23.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:30:23.423+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:30:23.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:30:23.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:30:23.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.175 seconds
[2024-07-02T16:31:09.085+0000] {processor.py:161} INFO - Started process (PID=3578) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:31:09.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:31:09.129+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:31:09.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:31:09.679+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:31:09.639+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:31:09.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:31:09.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.799 seconds
[2024-07-02T16:31:50.141+0000] {processor.py:161} INFO - Started process (PID=3665) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:31:50.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:31:50.166+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:31:50.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:31:50.332+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:31:50.308+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:31:50.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:31:50.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.285 seconds
[2024-07-02T16:32:37.795+0000] {processor.py:161} INFO - Started process (PID=3761) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:32:37.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:32:37.825+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:32:37.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:32:38.055+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:32:38.007+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:32:38.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:32:38.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.830 seconds
[2024-07-02T16:33:08.939+0000] {processor.py:161} INFO - Started process (PID=3849) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:33:08.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:33:09.099+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:33:09.083+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:33:09.581+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:33:09.542+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:33:09.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:33:09.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 1.131 seconds
[2024-07-02T16:33:47.853+0000] {processor.py:161} INFO - Started process (PID=3937) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:33:47.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:33:47.881+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:33:47.880+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:33:48.303+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:33:48.088+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:33:48.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:33:48.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.888 seconds
[2024-07-02T16:34:38.163+0000] {processor.py:161} INFO - Started process (PID=4031) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:34:38.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:34:38.187+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:34:38.185+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:34:38.343+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:34:38.324+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:34:38.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:34:38.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.292 seconds
[2024-07-02T16:35:08.968+0000] {processor.py:161} INFO - Started process (PID=4119) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:35:08.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:35:08.999+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:35:08.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:35:09.219+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:35:09.201+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:35:09.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:35:09.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.384 seconds
[2024-07-02T16:35:52.179+0000] {processor.py:161} INFO - Started process (PID=4207) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:35:52.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:35:52.194+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:35:52.193+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:35:52.389+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:35:52.361+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:35:52.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:35:52.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.332 seconds
[2024-07-02T16:36:25.670+0000] {processor.py:161} INFO - Started process (PID=4295) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:36:25.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:36:25.679+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:36:25.678+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:36:25.787+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:36:25.773+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:36:25.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:36:25.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.193 seconds
[2024-07-02T16:37:14.869+0000] {processor.py:161} INFO - Started process (PID=4389) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:37:14.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:37:14.887+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:37:14.886+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:37:15.044+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:37:15.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:37:15.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:37:15.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.273 seconds
[2024-07-02T16:37:42.766+0000] {processor.py:161} INFO - Started process (PID=4477) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:37:42.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:37:42.779+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:37:42.777+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:37:42.889+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:37:42.872+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:37:42.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:37:42.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.200 seconds
[2024-07-02T16:38:00.199+0000] {processor.py:161} INFO - Started process (PID=4559) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:00.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:38:00.212+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:00.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:00.335+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:00.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:38:00.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:00.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.196 seconds
[2024-07-02T16:38:16.914+0000] {processor.py:161} INFO - Started process (PID=4648) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:16.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:38:16.920+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:16.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:16.976+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:16.968+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:38:16.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:16.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.096 seconds
[2024-07-02T16:38:32.217+0000] {processor.py:161} INFO - Started process (PID=4730) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:32.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:38:32.227+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:32.226+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:32.308+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:32.298+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:38:32.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:32.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.140 seconds
[2024-07-02T16:38:49.505+0000] {processor.py:161} INFO - Started process (PID=4819) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:49.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:38:49.515+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:49.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:49.592+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:49.582+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:38:49.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:49.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.135 seconds
[2024-07-02T16:38:59.961+0000] {processor.py:161} INFO - Started process (PID=4901) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:38:59.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:38:59.970+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:38:59.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:00.067+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:00.055+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:39:00.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:00.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.162 seconds
[2024-07-02T16:39:15.139+0000] {processor.py:161} INFO - Started process (PID=4990) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:15.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:39:15.159+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:15.158+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:15.266+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:15.254+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:39:15.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:15.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.217 seconds
[2024-07-02T16:39:33.079+0000] {processor.py:161} INFO - Started process (PID=5072) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:33.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:39:33.087+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:33.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:33.163+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:33.153+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:39:33.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:33.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.132 seconds
[2024-07-02T16:39:45.887+0000] {processor.py:161} INFO - Started process (PID=5160) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:45.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:39:45.893+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:45.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:45.949+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:45.942+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:39:45.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:45.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.098 seconds
[2024-07-02T16:39:58.733+0000] {processor.py:161} INFO - Started process (PID=5242) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:58.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:39:58.742+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:58.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:58.819+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:39:58.810+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:39:58.823+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:39:58.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.136 seconds
[2024-07-02T16:40:09.997+0000] {processor.py:161} INFO - Started process (PID=5330) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:09.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:40:10.004+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:10.003+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:10.069+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:10.059+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:40:10.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:10.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.119 seconds
[2024-07-02T16:40:21.590+0000] {processor.py:161} INFO - Started process (PID=5412) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:21.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:40:21.600+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:21.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:21.681+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:21.671+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:40:21.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:21.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.135 seconds
[2024-07-02T16:40:33.654+0000] {processor.py:161} INFO - Started process (PID=5494) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:33.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:40:33.661+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:33.660+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:33.715+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:33.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:40:33.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:33.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.095 seconds
[2024-07-02T16:40:43.775+0000] {processor.py:161} INFO - Started process (PID=5583) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:43.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:40:43.781+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:43.780+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:43.841+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:43.834+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:40:43.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:43.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.101 seconds
[2024-07-02T16:40:53.133+0000] {processor.py:161} INFO - Started process (PID=5665) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:53.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:40:53.138+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:53.138+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:53.192+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:40:53.185+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:40:53.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:40:53.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.093 seconds
[2024-07-02T16:41:02.716+0000] {processor.py:161} INFO - Started process (PID=5747) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:02.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:41:02.722+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:02.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:02.780+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:02.774+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:41:02.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:02.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.100 seconds
[2024-07-02T16:41:12.139+0000] {processor.py:161} INFO - Started process (PID=5835) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:12.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:41:12.146+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:12.145+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:12.196+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:12.188+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:41:12.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:12.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.086 seconds
[2024-07-02T16:41:22.115+0000] {processor.py:161} INFO - Started process (PID=5917) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:22.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:41:22.122+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:22.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:22.171+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:22.165+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:41:22.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:22.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.087 seconds
[2024-07-02T16:41:30.302+0000] {processor.py:161} INFO - Started process (PID=5999) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:30.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:41:30.308+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:30.307+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:30.357+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:30.350+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:41:30.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:30.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.090 seconds
[2024-07-02T16:41:40.265+0000] {processor.py:161} INFO - Started process (PID=6087) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:40.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:41:40.273+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:40.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:40.326+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:40.319+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:41:40.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:40.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.101 seconds
[2024-07-02T16:41:49.665+0000] {processor.py:161} INFO - Started process (PID=6169) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:49.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:41:49.675+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:49.671+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:49.751+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:49.744+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:41:49.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:49.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.121 seconds
[2024-07-02T16:41:59.623+0000] {processor.py:161} INFO - Started process (PID=6251) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:59.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:41:59.629+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:59.628+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:59.676+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:41:59.671+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:41:59.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:41:59.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.087 seconds
[2024-07-02T16:42:08.755+0000] {processor.py:161} INFO - Started process (PID=6339) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:08.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:42:08.761+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:08.761+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:08.814+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:08.807+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:42:08.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:08.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.089 seconds
[2024-07-02T16:42:18.358+0000] {processor.py:161} INFO - Started process (PID=6421) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:18.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:42:18.364+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:18.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:18.408+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:18.401+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:42:18.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:18.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.082 seconds
[2024-07-02T16:42:27.140+0000] {processor.py:161} INFO - Started process (PID=6503) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:27.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:42:27.148+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:27.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:27.220+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:27.210+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:42:27.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:27.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.125 seconds
[2024-07-02T16:42:42.079+0000] {processor.py:161} INFO - Started process (PID=6592) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:42.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:42:42.082+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:42.082+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:42.133+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:42.125+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:42:42.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:42.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.085 seconds
[2024-07-02T16:42:53.832+0000] {processor.py:161} INFO - Started process (PID=6675) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:53.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:42:53.837+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:53.836+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:53.891+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:42:53.884+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:42:53.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:42:53.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.098 seconds
[2024-07-02T16:43:04.157+0000] {processor.py:161} INFO - Started process (PID=6758) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:04.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:43:04.161+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:04.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:04.218+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:04.209+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:43:04.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:04.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.097 seconds
[2024-07-02T16:43:16.398+0000] {processor.py:161} INFO - Started process (PID=6847) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:16.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:43:16.404+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:16.403+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:16.470+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:16.463+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:43:16.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:16.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.117 seconds
[2024-07-02T16:43:28.178+0000] {processor.py:161} INFO - Started process (PID=6930) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:28.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:43:28.190+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:28.189+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:28.290+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:28.274+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:43:28.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:28.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.191 seconds
[2024-07-02T16:43:40.791+0000] {processor.py:161} INFO - Started process (PID=7019) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:40.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:43:40.797+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:40.796+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:40.876+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:40.866+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:43:40.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:40.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.145 seconds
[2024-07-02T16:43:54.411+0000] {processor.py:161} INFO - Started process (PID=7102) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:54.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:43:54.415+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:54.415+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:54.467+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:43:54.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:43:54.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:43:54.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.089 seconds
[2024-07-02T16:44:04.608+0000] {processor.py:161} INFO - Started process (PID=7185) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:04.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:44:04.613+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:04.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:04.681+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:04.672+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:44:04.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:04.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.116 seconds
[2024-07-02T16:44:14.305+0000] {processor.py:161} INFO - Started process (PID=7274) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:14.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:44:14.309+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:14.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:14.357+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:14.351+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:44:14.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:14.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.085 seconds
[2024-07-02T16:44:25.276+0000] {processor.py:161} INFO - Started process (PID=7357) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:25.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:44:25.280+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:25.279+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:25.332+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:25.325+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:44:25.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:25.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.090 seconds
[2024-07-02T16:44:37.534+0000] {processor.py:161} INFO - Started process (PID=7440) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:37.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:44:37.538+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:37.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:37.599+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:37.590+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:44:37.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:37.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.106 seconds
[2024-07-02T16:44:49.199+0000] {processor.py:161} INFO - Started process (PID=7530) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:49.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:44:49.202+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:49.202+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:49.255+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:49.247+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:44:49.258+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:49.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.093 seconds
[2024-07-02T16:44:59.974+0000] {processor.py:161} INFO - Started process (PID=7613) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:44:59.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:44:59.978+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:44:59.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:00.039+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:00.031+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:45:00.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:00.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.101 seconds
[2024-07-02T16:45:09.385+0000] {processor.py:161} INFO - Started process (PID=7702) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:09.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:45:09.389+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:09.388+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:09.444+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:09.435+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:45:09.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:09.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.097 seconds
[2024-07-02T16:45:22.627+0000] {processor.py:161} INFO - Started process (PID=7785) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:22.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:45:22.631+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:22.630+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:22.684+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:22.675+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:45:22.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:22.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.089 seconds
[2024-07-02T16:45:34.136+0000] {processor.py:161} INFO - Started process (PID=7868) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:34.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:45:34.140+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:34.139+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:34.186+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:34.178+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:45:34.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:34.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.083 seconds
[2024-07-02T16:45:48.495+0000] {processor.py:161} INFO - Started process (PID=7957) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:48.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:45:48.501+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:48.500+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:48.551+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:45:48.543+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:45:48.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:45:48.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.091 seconds
[2024-07-02T16:46:03.156+0000] {processor.py:161} INFO - Started process (PID=8040) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:03.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:46:03.160+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:03.160+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:03.217+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:03.210+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:46:03.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:03.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.105 seconds
[2024-07-02T16:46:23.862+0000] {processor.py:161} INFO - Started process (PID=8129) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:23.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:46:23.867+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:23.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:23.935+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:23.926+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:46:23.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:23.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.126 seconds
[2024-07-02T16:46:39.577+0000] {processor.py:161} INFO - Started process (PID=8218) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:39.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:46:39.581+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:39.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:39.631+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:39.623+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:46:39.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:39.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.086 seconds
[2024-07-02T16:46:48.216+0000] {processor.py:161} INFO - Started process (PID=8301) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:48.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:46:48.219+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:48.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:48.273+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:48.264+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:46:48.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:48.293+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.088 seconds
[2024-07-02T16:46:58.223+0000] {processor.py:161} INFO - Started process (PID=8384) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:58.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:46:58.229+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:58.228+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:58.281+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:46:58.274+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:46:58.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:46:58.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.095 seconds
[2024-07-02T16:47:08.607+0000] {processor.py:161} INFO - Started process (PID=8473) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:08.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:47:08.611+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:08.611+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:08.668+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:08.661+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:47:08.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:08.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.100 seconds
[2024-07-02T16:47:18.237+0000] {processor.py:161} INFO - Started process (PID=8557) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:18.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:47:18.244+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:18.243+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:18.321+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:18.310+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:47:18.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:18.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.131 seconds
[2024-07-02T16:47:26.893+0000] {processor.py:161} INFO - Started process (PID=8640) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:26.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:47:26.897+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:26.897+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:26.952+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:26.943+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:47:26.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:26.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.092 seconds
[2024-07-02T16:47:37.268+0000] {processor.py:161} INFO - Started process (PID=8723) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:37.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:47:37.271+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:37.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:37.322+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:37.316+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:47:37.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:37.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.088 seconds
[2024-07-02T16:47:47.149+0000] {processor.py:161} INFO - Started process (PID=8812) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:47.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:47:47.154+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:47.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:47.211+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:47.205+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:47:47.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:47.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.096 seconds
[2024-07-02T16:47:57.902+0000] {processor.py:161} INFO - Started process (PID=8895) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:57.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:47:57.906+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:57.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:57.957+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:47:57.949+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:47:57.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:47:57.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.096 seconds
[2024-07-02T16:48:13.131+0000] {processor.py:161} INFO - Started process (PID=8984) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:13.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:48:13.136+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:13.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:13.362+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:13.326+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:48:13.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:13.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.561 seconds
[2024-07-02T16:48:26.873+0000] {processor.py:161} INFO - Started process (PID=9067) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:26.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:48:26.876+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:26.876+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:26.926+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:26.919+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:48:26.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:26.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.082 seconds
[2024-07-02T16:48:36.952+0000] {processor.py:161} INFO - Started process (PID=9151) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:36.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:48:36.956+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:36.955+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:37.003+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:36.997+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:48:37.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:37.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.094 seconds
[2024-07-02T16:48:53.133+0000] {processor.py:161} INFO - Started process (PID=9241) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:53.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:48:53.138+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:53.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:53.199+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:48:53.191+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_mysql_to_hive_all.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 7, in <module>
    list_table = Variable.get("mysql_to_hive", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable mysql_to_hive does not exist'
[2024-07-02T16:48:53.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:48:53.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.108 seconds
[2024-07-02T16:49:08.400+0000] {processor.py:161} INFO - Started process (PID=9330) to work on /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:49:08.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_mysql_to_hive_all.py for tasks to queue
[2024-07-02T16:49:08.404+0000] {logging_mixin.py:188} INFO - [2024-07-02T16:49:08.404+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:49:08.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_mysql_to_hive_all.py
[2024-07-02T16:49:08.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_mysql_to_hive_all.py took 0.055 seconds
