[2024-07-02T17:31:27.386+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: ingest_pet_adoption_data_to_mysql.ingest_csv_to_mysql scheduled__2023-01-02T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
