[2024-07-08T12:31:39.743+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: pet_adoption_etl.extract scheduled__2024-07-07T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
