[2024-07-07T06:35:25.837+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T06:35:25.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pet_adoption_etl.check_file_exists manual__2024-07-07T06:33:56.236290+00:00 [queued]>
[2024-07-07T06:35:25.934+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pet_adoption_etl.check_file_exists manual__2024-07-07T06:33:56.236290+00:00 [queued]>
[2024-07-07T06:35:25.940+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-07T06:35:25.984+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_file_exists> on 2024-07-07 06:33:56.236290+00:00
[2024-07-07T06:35:25.996+0000] {standard_task_runner.py:63} INFO - Started process 673 to run task
[2024-07-07T06:35:26.002+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pet_adoption_etl', 'check_file_exists', 'manual__2024-07-07T06:33:56.236290+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/pet_adoption_ingest.py', '--cfg-path', '/tmp/tmpnkvg53_m']
[2024-07-07T06:35:26.010+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask check_file_exists
[2024-07-07T06:35:26.100+0000] {task_command.py:426} INFO - Running <TaskInstance: pet_adoption_etl.check_file_exists manual__2024-07-07T06:33:56.236290+00:00 [running]> on host 8b51af410d55
[2024-07-07T06:35:26.508+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pet_adoption_etl' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T06:33:56.236290+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T06:33:56.236290+00:00'
[2024-07-07T06:35:26.535+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T06:35:26.546+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T06:35:26.550+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pet_adoption_ingest.py", line 27, in check_file_exists
    raise FileNotFoundError("pet_adoption_data.csv not found in the data folder")
FileNotFoundError: pet_adoption_data.csv not found in the data folder
[2024-07-07T06:35:26.602+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pet_adoption_etl, task_id=check_file_exists, run_id=manual__2024-07-07T06:33:56.236290+00:00, execution_date=20240707T063356, start_date=20240707T063525, end_date=20240707T063526
[2024-07-07T06:35:26.660+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 206 for task check_file_exists (pet_adoption_data.csv not found in the data folder; 673)
[2024-07-07T06:35:26.712+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T06:35:26.764+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-07T06:35:26.833+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T06:35:26.850+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
