[2024-05-11T18:09:39.642+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T18:09:39.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mysql_to_hive_all.dibimbing__position.transform_with_python manual__2024-05-11T18:09:25.933515+00:00 [queued]>
[2024-05-11T18:09:39.690+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mysql_to_hive_all.dibimbing__position.transform_with_python manual__2024-05-11T18:09:25.933515+00:00 [queued]>
[2024-05-11T18:09:39.691+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-11T18:09:39.714+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): dibimbing__position.transform_with_python> on 2024-05-11 18:09:25.933515+00:00
[2024-05-11T18:09:39.725+0000] {standard_task_runner.py:63} INFO - Started process 9680 to run task
[2024-05-11T18:09:39.729+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_mysql_to_hive_all', 'dibimbing__position.transform_with_python', 'manual__2024-05-11T18:09:25.933515+00:00', '--job-id', '885', '--raw', '--subdir', 'DAGS_FOLDER/etl_mysql_to_hive_all.py', '--cfg-path', '/tmp/tmp5pftb3ik']
[2024-05-11T18:09:39.734+0000] {standard_task_runner.py:91} INFO - Job 885: Subtask dibimbing__position.transform_with_python
[2024-05-11T18:09:39.808+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_mysql_to_hive_all.dibimbing__position.transform_with_python manual__2024-05-11T18:09:25.933515+00:00 [running]> on host 94409fb18ddd
[2024-05-11T18:09:39.960+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_mysql_to_hive_all' AIRFLOW_CTX_TASK_ID='dibimbing__position.transform_with_python' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T18:09:25.933515+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T18:09:25.933515+00:00'
[2024-05-11T18:09:39.963+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T18:09:39.964+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T18:09:39.965+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 57, in transform
    context = get_current_context()
              ^^^^^^^^^^^^^^^^^^^
NameError: name 'get_current_context' is not defined
[2024-05-11T18:09:39.982+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_mysql_to_hive_all, task_id=dibimbing__position.transform_with_python, run_id=manual__2024-05-11T18:09:25.933515+00:00, execution_date=20240511T180925, start_date=20240511T180939, end_date=20240511T180939
[2024-05-11T18:09:40.000+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 885 for task dibimbing__position.transform_with_python (name 'get_current_context' is not defined; 9680)
[2024-05-11T18:09:40.018+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-11T18:09:40.058+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-11T18:09:40.066+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
