[2024-07-10T14:45:39.519+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T14:45:39.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pet_adoption_dag.extract_csv manual__2024-07-10T14:45:33.284215+00:00 [queued]>
[2024-07-10T14:45:39.589+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pet_adoption_dag.extract_csv manual__2024-07-10T14:45:33.284215+00:00 [queued]>
[2024-07-10T14:45:39.591+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-10T14:45:39.625+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-07-10 14:45:33.284215+00:00
[2024-07-10T14:45:39.636+0000] {standard_task_runner.py:63} INFO - Started process 341 to run task
[2024-07-10T14:45:39.643+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pet_adoption_dag', 'extract_csv', 'manual__2024-07-10T14:45:33.284215+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pet_adoption_dag.py', '--cfg-path', '/tmp/tmp9ilvndsc']
[2024-07-10T14:45:39.648+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract_csv
[2024-07-10T14:45:39.871+0000] {task_command.py:426} INFO - Running <TaskInstance: pet_adoption_dag.extract_csv manual__2024-07-10T14:45:33.284215+00:00 [running]> on host 9227fc3503c5
[2024-07-10T14:45:40.256+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pet_adoption_dag' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T14:45:33.284215+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-10T14:45:33.284215+00:00'
[2024-07-10T14:45:40.258+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T14:45:40.272+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T14:45:40.274+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pet_adoption_dag.py", line 18, in read_csv_file
    df = pd.read_csv(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/pet_adoption_data.csv'
[2024-07-10T14:45:40.317+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=pet_adoption_dag, task_id=extract_csv, run_id=manual__2024-07-10T14:45:33.284215+00:00, execution_date=20240710T144533, start_date=20240710T144539, end_date=20240710T144540
[2024-07-10T14:45:40.344+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task extract_csv ([Errno 2] No such file or directory: '/opt/data/pet_adoption_data.csv'; 341)
[2024-07-10T14:45:40.381+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T14:45:40.430+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T14:45:40.434+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
