[2024-07-08T14:01:08.817+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T14:01:08.877+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pet_adoption_etl.check_file_exists manual__2024-07-08T13:49:38.865938+00:00 [queued]>
[2024-07-08T14:01:08.901+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pet_adoption_etl.check_file_exists manual__2024-07-08T13:49:38.865938+00:00 [queued]>
[2024-07-08T14:01:08.903+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T14:01:08.974+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_file_exists> on 2024-07-08 13:49:38.865938+00:00
[2024-07-08T14:01:08.988+0000] {standard_task_runner.py:63} INFO - Started process 61 to run task
[2024-07-08T14:01:08.997+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pet_adoption_etl', 'check_file_exists', 'manual__2024-07-08T13:49:38.865938+00:00', '--job-id', '1023', '--raw', '--subdir', 'DAGS_FOLDER/pet_adoption_ingest.py', '--cfg-path', '/tmp/tmp6hxb_odx']
[2024-07-08T14:01:09.011+0000] {standard_task_runner.py:91} INFO - Job 1023: Subtask check_file_exists
[2024-07-08T14:01:09.167+0000] {task_command.py:426} INFO - Running <TaskInstance: pet_adoption_etl.check_file_exists manual__2024-07-08T13:49:38.865938+00:00 [running]> on host 1493cc9eac54
[2024-07-08T14:01:09.444+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pet_adoption_etl' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T13:49:38.865938+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T13:49:38.865938+00:00'
[2024-07-08T14:01:09.451+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T14:01:09.453+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T14:01:09.455+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pet_adoption_ingest.py", line 27, in check_file_exists
    raise FileNotFoundError("pet_adoption_data.csv not found in the data folder")
FileNotFoundError: pet_adoption_data.csv not found in the data folder
[2024-07-08T14:01:09.491+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=pet_adoption_etl, task_id=check_file_exists, run_id=manual__2024-07-08T13:49:38.865938+00:00, execution_date=20240708T134938, start_date=20240708T140108, end_date=20240708T140109
[2024-07-08T14:01:09.531+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1023 for task check_file_exists (pet_adoption_data.csv not found in the data folder; 61)
[2024-07-08T14:01:09.579+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T14:01:09.605+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-08T14:01:09.650+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T14:01:09.655+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
