[2024-07-07T06:38:02.755+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: pet_adoption_etl.check_file_exists manual__2024-07-06T18:36:04.151440+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-07T06:38:25.849+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: pet_adoption_etl.check_file_exists manual__2024-07-06T18:36:04.151440+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
