[2024-07-08T15:09:58.932+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T15:09:59.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pet_adoption_mysql_ingest.create_table scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-07-08T15:09:59.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pet_adoption_mysql_ingest.create_table scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-07-08T15:09:59.114+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-08T15:09:59.190+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): create_table> on 2024-01-03 00:00:00+00:00
[2024-07-08T15:09:59.224+0000] {standard_task_runner.py:63} INFO - Started process 986 to run task
[2024-07-08T15:09:59.231+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pet_adoption_mysql_ingest', 'create_table', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '1053', '--raw', '--subdir', 'DAGS_FOLDER/pet_adoption_etl.py', '--cfg-path', '/tmp/tmpa40hcg3u']
[2024-07-08T15:09:59.238+0000] {standard_task_runner.py:91} INFO - Job 1053: Subtask create_table
[2024-07-08T15:09:59.481+0000] {task_command.py:426} INFO - Running <TaskInstance: pet_adoption_mysql_ingest.create_table scheduled__2024-01-03T00:00:00+00:00 [running]> on host 1493cc9eac54
[2024-07-08T15:09:59.943+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pet_adoption_mysql_ingest' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-07-08T15:09:59.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T15:09:59.961+0000] {sql.py:276} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS pet_adoptions (
        PetID INT PRIMARY KEY,
        PetType VARCHAR(50),
        Breed VARCHAR(100),
        AgeMonths INT,
        AgeYears FLOAT,
        Color VARCHAR(50),
        SizeCategory CHAR(1),
        WeightKg FLOAT,
        IsVaccinated VARCHAR(3),
        HealthStatus VARCHAR(10),
        TimeInShelterDays INT,
        AdoptionCost VARCHAR(10),
        PreviousOwner INT,
        AdoptionProbability VARCHAR(10)
    )
    
[2024-07-08T15:10:00.002+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T15:10:00.047+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_default` isn't defined
[2024-07-08T15:10:00.084+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pet_adoption_mysql_ingest, task_id=create_table, run_id=scheduled__2024-01-03T00:00:00+00:00, execution_date=20240103T000000, start_date=20240708T150959, end_date=20240708T151000
[2024-07-08T15:10:00.140+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1053 for task create_table (The conn_id `mysql_default` isn't defined; 986)
[2024-07-08T15:10:00.190+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T15:10:00.227+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
