[2024-07-13T17:20:13.493+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: pet_adoption_dag.verify_path manual__2024-07-13T17:20:12.197090+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
